-- MySQL Script generated by MySQL Workbench
-- 10/18/14 09:42:29
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema concurso
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `concurso` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `concurso` ;

-- -----------------------------------------------------
-- Table `concurso`.`tb_candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concurso`.`tb_candidato` (
  `can_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `can_nome` VARCHAR(255) NOT NULL,
  `can_cpf` VARCHAR(14) NOT NULL,
  `can_login` VARCHAR(45) NOT NULL,
  `can_senha` VARCHAR(45) NOT NULL,
  `can_foto` VARCHAR(45) NULL,
  PRIMARY KEY (`can_id`, `can_cpf`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concurso`.`tb_concursos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concurso`.`tb_concursos` (
  `con_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `con_titulo` VARCHAR(255) NOT NULL,
  `con_descricao` TEXT NOT NULL,
  `con_situacao` INT ZEROFILL NOT NULL DEFAULT 0 COMMENT '0 - Aberto' /* comment truncated */ /*1 - Em andamento
2 - Encerrada inscrição*/,
  `con_data` DATE NULL,
  `con_inscricao` DATE NULL,
  PRIMARY KEY (`con_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concurso`.`tb_tipo_documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concurso`.`tb_tipo_documento` (
  `tipdoc_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tipdoc_descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tipdoc_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concurso`.`tb_arquivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concurso`.`tb_arquivo` (
  `arq_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `arq_titulo` VARCHAR(255) NOT NULL,
  `arq_arquivo` VARCHAR(45) NOT NULL,
  `atualizacao` TIMESTAMP NOT NULL,
  `tipdoc_id` INT UNSIGNED NOT NULL,
  `con_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`arq_id`, `tipdoc_id`, `con_id`),
  INDEX `fk_tb_arquivo_tb_tipo_documento1_idx` (`tipdoc_id` ASC),
  INDEX `fk_tb_arquivo_tb_concursos1_idx` (`con_id` ASC),
  CONSTRAINT `fk_tb_arquivo_tb_tipo_documento1`
    FOREIGN KEY (`tipdoc_id`)
    REFERENCES `concurso`.`tb_tipo_documento` (`tipdoc_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_arquivo_tb_concursos1`
    FOREIGN KEY (`con_id`)
    REFERENCES `concurso`.`tb_concursos` (`con_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concurso`.`tb_vagas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concurso`.`tb_vagas` (
  `vag_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `vag_cargo` VARCHAR(45) NOT NULL,
  `vag_descricao` TEXT NOT NULL,
  `vag_qtd` INT NOT NULL DEFAULT 0,
  `vag_salario` FLOAT NOT NULL DEFAULT 0,
  `vag_escolaridade` INT NOT NULL DEFAULT 0,
  `vag_valor` FLOAT NULL DEFAULT 0,
  `con_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`vag_id`, `con_id`),
  INDEX `fk_tb_vagas_tb_concursos1_idx` (`con_id` ASC),
  CONSTRAINT `fk_tb_vagas_tb_concursos1`
    FOREIGN KEY (`con_id`)
    REFERENCES `concurso`.`tb_concursos` (`con_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concurso`.`tb_inscricoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concurso`.`tb_inscricoes` (
  `ins_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `ins_data` TIMESTAMP NOT NULL,
  `ins_situacao` INT NOT NULL DEFAULT 0 COMMENT '0 - Em aberto' /* comment truncated */ /*1 - Pago*/,
  `ins_nota` FLOAT NOT NULL DEFAULT 0,
  `can_id` INT UNSIGNED NOT NULL,
  `con_id` INT UNSIGNED NOT NULL,
  `vag_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`ins_id`, `can_id`, `con_id`, `vag_id`),
  INDEX `fk_tb_inscricoes_tb_candidato_idx` (`can_id` ASC),
  INDEX `fk_tb_inscricoes_tb_concursos1_idx` (`con_id` ASC),
  INDEX `fk_tb_inscricoes_tb_vagas1_idx` (`vag_id` ASC),
  CONSTRAINT `fk_tb_inscricoes_tb_candidato`
    FOREIGN KEY (`can_id`)
    REFERENCES `concurso`.`tb_candidato` (`can_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_inscricoes_tb_concursos1`
    FOREIGN KEY (`con_id`)
    REFERENCES `concurso`.`tb_concursos` (`con_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tb_inscricoes_tb_vagas1`
    FOREIGN KEY (`vag_id`)
    REFERENCES `concurso`.`tb_vagas` (`vag_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `concurso`.`tb_admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `concurso`.`tb_admin` (
  `adm_id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `adm_login` VARCHAR(45) NOT NULL,
  `adm_senha` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`adm_id`, `adm_login`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
